### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by maxwell-oroark** [sharpshark28/modern-terminal-workflow#2]
First off I should say I followed your guide and thought it was fantastic. I now have my dream setup for mac osx and couldn't be happier, so thank you.

My question is about the feasibility of getting this same setup on ubuntu?  I just built this PC but have never really worked with linux much, I think a lot of these things are available for ubuntu; zsh, nvim, etc. but some of them are for sure not, like Iterm2.

Do you have any insight on what kind of modifications would be necessary to achieve a similar set up on modern ubuntu?

Thanks!

**Comment by hergaiety** [comment]
Hey @maxwell-oroark thanks for your interest and taking the time to write to me.

I haven't had the luxury of dev'ing in a linux environment in a long time as my recent jobs have had me using OSX or Windows.

That being said, as you've mentioned many tools work very well and perhaps even better on Ubuntu. For shells you can choose from Bash, Zsh or Fish for example. Neovim and Tmux supposedly work great. For iTerm2 alternatives there are options like guake or Terminator but I haven't used any of these personally.

[Jarrod Taylor](https://github.com/JarrodCTaylor/) has a very robust [dotfiles](https://github.com/JarrodCTaylor/dotfiles) that supports both OSX and Linux. Your best bet may be to fork either Jarrod's or this repo's dotfiles and make it your own!

Best wishes to you and let me know how it goes.

**Comment by maxwell-oroark** [comment]
Thanks for the swift reply! I will check out Jarrod's dotfile for sure and try and report back!
